// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAywGsDEFru4AJVzoJozuJewVUpbcenPfE',
    appId: '1:286284015485:web:824f885cfa9f615bb5ce14',
    messagingSenderId: '286284015485',
    projectId: 'semesterproject-152cb',
    authDomain: 'semesterproject-152cb.firebaseapp.com',
    databaseURL: 'https://semesterproject-152cb-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-152cb.firebasestorage.app',
    measurementId: 'G-QDBTQE8NR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUT5aV6hnTAFWqo16xpkDPm3GCZqzqr1k',
    appId: '1:286284015485:android:36d3cc0ce4485552b5ce14',
    messagingSenderId: '286284015485',
    projectId: 'semesterproject-152cb',
    databaseURL: 'https://semesterproject-152cb-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-152cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAANTy07ton6A2_3rEbGYJ7wrnxtlWY-04',
    appId: '1:286284015485:ios:433a8c5af2dfa5a5b5ce14',
    messagingSenderId: '286284015485',
    projectId: 'semesterproject-152cb',
    databaseURL: 'https://semesterproject-152cb-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-152cb.firebasestorage.app',
    iosBundleId: 'com.example.semproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAANTy07ton6A2_3rEbGYJ7wrnxtlWY-04',
    appId: '1:286284015485:ios:433a8c5af2dfa5a5b5ce14',
    messagingSenderId: '286284015485',
    projectId: 'semesterproject-152cb',
    databaseURL: 'https://semesterproject-152cb-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-152cb.firebasestorage.app',
    iosBundleId: 'com.example.semproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAywGsDEFru4AJVzoJozuJewVUpbcenPfE',
    appId: '1:286284015485:web:6400fd1ff5d54d13b5ce14',
    messagingSenderId: '286284015485',
    projectId: 'semesterproject-152cb',
    authDomain: 'semesterproject-152cb.firebaseapp.com',
    databaseURL: 'https://semesterproject-152cb-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-152cb.firebasestorage.app',
    measurementId: 'G-KTKEKTRZD9',
  );

}